### PR TITLE
serilog config

### LINKED ISSUE #38: Add Serilog for logging

### PR DESCRIPTION
**Pull request by chrisK00**
closes #38

### CODE REVIEW

**Review by JoyfulReaper — COMMENTED** [review]
Shouldn't line 61 be something like:

services.AddLogging(configure => configure.AddSerilog())

**Comment by chrisK00** [comment]
> Shouldn't line 61 be something like:
> 
> services.AddLogging(configure => configure.AddSerilog())

Makes more sense, do you know what the difference is? Ive only done it before with the former way

**Comment by JoyfulReaper** [comment]
Pretty sure .AddSerilog() is an extension method that is part of the library. Like this from one of my own projects:

    public static class ServiceCollectionExtensions
    {
        public static IServiceCollection AddHappyIrcClient(this IServiceCollection services)
        {
            services
           .AddTransient<ITcpClient, TcpClient>()
           .AddSingleton<IMessageParser, MessageParser>()
           .AddTransient<IIrcClient, IrcClient>();
            return services;
        }
    }

**Comment by chrisK00** [comment]
> Pretty sure .AddSerilog() is an extension method that is part of the library. Like this from one of my own projects:
> 
> ```
> public static class ServiceCollectionExtensions
> {
>     public static IServiceCollection AddHappyIrcClient(this IServiceCollection services)
>     {
>         services
>        .AddTransient<ITcpClient, TcpClient>()
>        .AddSingleton<IMessageParser, MessageParser>()
>        .AddTransient<IIrcClient, IrcClient>();
>         return services;
>     }
> }
> ```

We use it the normal way tho yeh? Like Inject a ILogger<type> then logger.error or whatevs?

**Comment by chrisK00** [comment]
will let reaper replace current logging instead

**Pull request closed without merging**
